# Medium Tests: Run on all commits/PRs to dev branch

language: c
dist: trusty

git:
  depth: 1

branches:
  only:
  - dev
  - master
  - travisTest

addons:
  apt:
    update: true

env:
  global:
    - FUZZERTEST=-T2mn
      ZSTREAM_TESTTIME=-T2mn
      DECODECORPUS_TESTTIME=-T1mn


matrix:
  fast_finish: true
  include:
    - name: arm64
      os: linux
      arch: arm64
      script:
        - make check

    - name: amd64
      os: linux
      arch: amd64
      script:
        - make test

  allow_failures:
    - env: ALLOW_FAILURES=true
